
<center>
<hr>
<hr>
<font style="font-size:5.4em ; color:black'" > 
<span style="background : yellow">
#5 Algebra, Matrix Solvers
</span>
</font>
<hr>
<hr>
</center>


In [125]:
%matplotlib inline
from IPython.display import display,Latex,Math,HTML
import sympy as sym
import scipy as sp
import math
import matplotlib.pyplot as plt
import matplotlib.animation as animation
import numpy as np

In [126]:
x = np.array([1,1])
mat = np.array([[4,2],[2,4]])
vec_b = np.dot(mat,x)
print(mat)
print(vec_b)
P, L, U = sp.linalg.lu(mat)
print("P:\n", P)
print("L:\n", L)
print("U:\n", U)

[[4 2]
 [2 4]]
[6 6]
P:
 [[1. 0.]
 [0. 1.]]
L:
 [[1.  0. ]
 [0.5 1. ]]
U:
 [[4. 2.]
 [0. 3.]]


In [127]:
Latex(f""" \\begin{{equation*}}
            \\begin{{bmatrix*}} 
                  \\Huge {{{mat[0,0]}}} & \\Huge {{{mat[0,1]}}} \\\\[1em]
                  \\Huge {{{mat[1,0]}}} & \\Huge {{{mat[1,1]}}} 
            \\end{{bmatrix*}} 
            \\begin{{bmatrix*}}
                  \\Huge a_1\\\\[1.8em]
                  \\Huge a_2
            \\end{{bmatrix*}}=
            \\begin{{bmatrix*}}
                  \\Huge {{{vec_b[0]}}}\\\\[1em]
                  \\Huge {{{vec_b[1]}}}
            \\end{{bmatrix*}}
      \\end{{equation*}}
""")

<IPython.core.display.Latex object>

In [128]:
Latex(f""" \\begin{{equation*}}
            \\begin{{bmatrix*}}
                  \\Huge a_1\\\\[1.8em]
                  \\Huge a_2
            \\end{{bmatrix*}}=
            \\begin{{bmatrix*}}
                  \\Huge {{{x[0]}}}\\\\[1em]
                  \\Huge {{{x[1]}}}
            \\end{{bmatrix*}}
      \\end{{equation*}}
""")

<IPython.core.display.Latex object>

In [129]:
x = np.array([1,1,1])
mat = np.array([[4,2,1],[2,4,1],[2,1,4]])
vec_b = np.dot(mat,x)
print(mat)
print(vec_b)
P, L, U = sp.linalg.lu(mat)
print("P:\n", P)
print("L:\n", L)
print("U:\n", U)

[[4 2 1]
 [2 4 1]
 [2 1 4]]
[7 7 7]
P:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
L:
 [[1.  0.  0. ]
 [0.5 1.  0. ]
 [0.5 0.  1. ]]
U:
 [[4.  2.  1. ]
 [0.  3.  0.5]
 [0.  0.  3.5]]


In [130]:
Latex(f""" \\begin{{equation*}}
            \\begin{{bmatrix*}} 
                  \\Huge {{{mat[0,0]}}} & \\Huge {{{mat[0,1]}}} & \\Huge {{{mat[0,2]}}}\\\\[1em]
                  \\Huge {{{mat[1,0]}}} & \\Huge {{{mat[1,1]}}} & \\Huge {{{mat[1,2]}}}\\\\[1em]
                  \\Huge {{{mat[2,0]}}} & \\Huge {{{mat[2,1]}}} & \\Huge {{{mat[2,2]}}}      
            \\end{{bmatrix*}} 
            \\begin{{bmatrix*}}
                  \\Huge a_1\\\\[1.8em]
                  \\Huge a_2\\\\[1.8em]
                  \\Huge a_3
            \\end{{bmatrix*}}=
            \\begin{{bmatrix*}}
                  \\Huge {{{vec_b[0]}}}\\\\[1em]
                  \\Huge {{{vec_b[1]}}}\\\\[1em]
                  \\Huge {{{vec_b[2]}}}
            \\end{{bmatrix*}}
      \\end{{equation*}}
""")

<IPython.core.display.Latex object>

In [131]:
Latex(f""" \\begin{{equation*}}
            \\begin{{bmatrix*}}
                  \\Huge a_1\\\\[1.8em]
                  \\Huge a_2\\\\[1.8em]
                  \\Huge a_3
            \\end{{bmatrix*}}=
            \\begin{{bmatrix*}}
                  \\Huge {{{x[0]}}}\\\\[1em]
                  \\Huge {{{x[1]}}}\\\\[1em]                  
                  \\Huge {{{x[2]}}}
            \\end{{bmatrix*}}
      \\end{{equation*}}
""")

<IPython.core.display.Latex object>

<center>
<hr>
<font size="20" color='Blue' >Gauss Elimination</font>
<hr>
</center>

In [132]:
mat = np.array([[25,5,1],[64,8,1],[144,12,1]])
vec_b = np.array([106.8,177.2,279.2])
print(mat)
print(vec_b)

[[ 25   5   1]
 [ 64   8   1]
 [144  12   1]]
[106.8 177.2 279.2]


In [133]:
Latex(f""" \\begin{{equation*}}
            \\begin{{bmatrix*}} 
                  \\Huge {{{mat[0,0]}}} & \\Huge {{{mat[0,1]}}} & \\Huge {{{mat[0,2]}}}\\\\[1em]
                  \\Huge {{{mat[1,0]}}} & \\Huge {{{mat[1,1]}}} & \\Huge {{{mat[1,2]}}}\\\\[1em]
                  \\Huge {{{mat[2,0]}}} & \\Huge {{{mat[2,1]}}} & \\Huge {{{mat[2,2]}}}      
            \\end{{bmatrix*}} 
            \\begin{{bmatrix*}}
                  \\Huge a_1\\\\[1.8em]
                  \\Huge a_2\\\\[1.8em]
                  \\Huge a_3
            \\end{{bmatrix*}}=
            \\begin{{bmatrix*}}
                  \\Huge {{{vec_b[0]}}}\\\\[1em]
                  \\Huge {{{vec_b[1]}}}\\\\[1em]
                  \\Huge {{{vec_b[2]}}}
            \\end{{bmatrix*}}
      \\end{{equation*}}
""")

<IPython.core.display.Latex object>

In [134]:

 
n = 3
a = np.concatenate((mat,vec_b.reshape(-1,1)),axis=1)

x = np.zeros(n)
print('forward elimination\n')
for i in range(n):
    print(a,end='\n\n')
    for j in range(i+1, n):
        ratio = a[j][i]/a[i][i]
         
        for k in range(n+1):
            a[j][k] = a[j][k] - ratio * a[i][k]
 
print('backward substitution\n')
x[n-1] = a[n-1][n]/a[n-1][n-1]
print(f"x[{n-1}] = {a[n-1][n]}/{a[n-1][n-1]} = {x[n-1]}",end='\n\n')
for i in range(n-2,-1,-1):
    x[i] = a[i][n]
    t=0 
    for j in range(i+1,n):
        x[i] = x[i] - a[i][j]*x[j]
        t += a[i][j]*x[j]
     
    x[i] = x[i]/a[i][i]
    sign = '+' if t<0 else '-'
    print(f"x[{i}] = ({a[i][n]} {sign} {abs(t)})/{a[i][i]} = {x[i]}", end='\n\n')
print('\nThe solution is: ')
for i in range(n):
    print('X%d = %0.5f' %(i,x[i]), end = '\t')
x_bk = x

forward elimination

[[ 25.    5.    1.  106.8]
 [ 64.    8.    1.  177.2]
 [144.   12.    1.  279.2]]

[[  25.       5.       1.     106.8  ]
 [   0.      -4.8     -1.56   -96.208]
 [   0.     -16.8     -4.76  -335.968]]

[[ 25.      5.      1.    106.8  ]
 [  0.     -4.8    -1.56  -96.208]
 [  0.      0.      0.7     0.76 ]]

backward substitution

x[2] = 0.7599999999999909/0.6999999999999993 = 1.0857142857142739

x[1] = (-96.20800000000003 + 1.6937142857142673)/-4.800000000000001 = 19.690476190476197

x[0] = (106.8 - 99.53809523809527)/25.0 = 0.2904761904761893


The solution is: 
X0 = 0.29048	X1 = 19.69048	X2 = 1.08571	

<center>
<hr>
<font size="20" color='Blue' >Gauss Elimination with Pivot </font>
<hr>
</center>

In [135]:
# Example to show the potential problem of naive Gauss elimination
mat = np.array([[1e-20, 1], [1, 1]])
vec_b = np.array([1, 2])

print("Matrix (A):")
print(mat)
print("\nVector (b):")
print(vec_b)

# Augmented matrix
augmented_mat = np.concatenate((mat, vec_b.reshape(-1, 1)), axis=1)

print("\nAugmented Matrix [A|b]:")
print(augmented_mat)

# Forward elimination without pivoting
n = len(vec_b)
for i in range(n):
    for j in range(i + 1, n):
        factor = augmented_mat[j, i] / augmented_mat[i, i]
        augmented_mat[j, i:] -= factor * augmented_mat[i, i:]

print("\nAugmented Matrix after Forward Elimination (Naive):")
print(augmented_mat)

# Back substitution
x = np.zeros(n)
x[-1] = augmented_mat[-1, -1] / augmented_mat[-1, -2]
for i in range(n - 2, -1, -1):
    x[i] = (augmented_mat[i, -1] - np.dot(augmented_mat[i, i + 1:n], x[i + 1:])) / augmented_mat[i, i]

print("\nSolution (x):")
print(x)

# Note: The solution may be inaccurate due to the lack of partial pivoting.

Matrix (A):
[[1.e-20 1.e+00]
 [1.e+00 1.e+00]]

Vector (b):
[1 2]

Augmented Matrix [A|b]:
[[1.e-20 1.e+00 1.e+00]
 [1.e+00 1.e+00 2.e+00]]

Augmented Matrix after Forward Elimination (Naive):
[[ 1.e-20  1.e+00  1.e+00]
 [ 0.e+00 -1.e+20 -1.e+20]]

Solution (x):
[0. 1.]


In [136]:
mat = np.array([[144,12,1],[64,8,1],[25,5,1]])
vec_b = np.array([279.2,177.2,106.8])
print(mat)
print(vec_b)

[[144  12   1]
 [ 64   8   1]
 [ 25   5   1]]
[279.2 177.2 106.8]


In [137]:
Latex(f""" \\begin{{equation*}}
            \\begin{{bmatrix*}} 
                  \\Huge {{{mat[0,0]}}} & \\Huge {{{mat[0,1]}}} & \\Huge {{{mat[0,2]}}}\\\\[1em]
                  \\Huge {{{mat[1,0]}}} & \\Huge {{{mat[1,1]}}} & \\Huge {{{mat[1,2]}}}\\\\[1em]
                  \\Huge {{{mat[2,0]}}} & \\Huge {{{mat[2,1]}}} & \\Huge {{{mat[2,2]}}}      
            \\end{{bmatrix*}} 
            \\begin{{bmatrix*}}
                  \\Huge a_1\\\\[1.8em]
                  \\Huge a_2\\\\[1.8em]
                  \\Huge a_3
            \\end{{bmatrix*}}=
            \\begin{{bmatrix*}}
                  \\Huge {{{vec_b[0]}}}\\\\[1em]
                  \\Huge {{{vec_b[1]}}}\\\\[1em]
                  \\Huge {{{vec_b[2]}}}
            \\end{{bmatrix*}}
      \\end{{equation*}}
""")

<IPython.core.display.Latex object>

In [138]:
def rnd(x,n=2):
    t = 10**n
    return math.floor(x*t)/t

n = 3
a = np.concatenate((mat,vec_b.reshape(-1,1)),axis=1)

x = np.zeros(n)
print('forward elimination\n')
for i in range(n):
    print(a,end='\n\n')
    for j in range(i+1, n):
        ratio = a[j][i]/a[i][i]
         
        for k in range(n+1):
            a[j][k] = a[j][k] - ratio * a[i][k]
 
print('backward substitution\n')
a[n-1][n]=rnd(a[n-1][n])
a[n-1][n-1]=rnd(a[n-1][n-1],1)
x[n-1] = rnd(a[n-1][n])/rnd(a[n-1][n-1])
print(f"x[{n-1}] = {a[n-1][n]}/{a[n-1][n-1]} = {x[n-1]}",end='\n\n')
for i in range(n-2,-1,-1):
    x[i] = a[i][n]
    t=0 
    for j in range(i+1,n):
        x[i] = x[i] - a[i][j]*x[j]
        t += a[i][j]*x[j]
     
    x[i] = x[i]/a[i][i]
    sign = '+' if t<0 else '-'
    print(f"x[{i}] = ({a[i][n]} {sign} {abs(t)})/{a[i][i]} = {x[i]}", end='\n\n')
print('\nThe solution is: ')
for i in range(n):
    print('X%d = %0.5f' %(i,x[i]), end = '\t')

forward elimination

[[144.   12.    1.  279.2]
 [ 64.    8.    1.  177.2]
 [ 25.    5.    1.  106.8]]

[[144.          12.           1.         279.2       ]
 [  0.           2.66666667   0.55555556  53.11111111]
 [  0.           2.91666667   0.82638889  58.32777778]]

[[1.44000000e+02 1.20000000e+01 1.00000000e+00 2.79200000e+02]
 [0.00000000e+00 2.66666667e+00 5.55555556e-01 5.31111111e+01]
 [0.00000000e+00 0.00000000e+00 2.18750000e-01 2.37500000e-01]]

backward substitution

x[2] = 0.23/0.2 = 1.15

x[1] = (53.111111111111114 - 0.6388888888888888)/2.666666666666667 = 19.677083333333332

x[0] = (279.2 - 237.275)/144.0 = 0.29114583333333327


The solution is: 
X0 = 0.29115	X1 = 19.67708	X2 = 1.15000	

In [139]:
n = 3
a = np.concatenate((mat,vec_b.reshape(-1,1)),axis=1)

x = np.zeros(n)
print('forward elimination\n')
for i in range(n):
    print(a,end='\n\n')
    for j in range(i+1, n):
        ratio = a[j][i]/a[i][i]
         
        for k in range(n+1):
            a[j][k] = a[j][k] - ratio * a[i][k]
 
print('backward substitution\n')
x[n-1] = a[n-1][n]/a[n-1][n-1]
print(f"x[{n-1}] = {a[n-1][n]}/{a[n-1][n-1]} = {x[n-1]}",end='\n\n')
for i in range(n-2,-1,-1):
    x[i] = a[i][n]
    t=0 
    for j in range(i+1,n):
        x[i] = x[i] - a[i][j]*x[j]
        t += a[i][j]*x[j]
     
    x[i] = x[i]/a[i][i]
    sign = '+' if t<0 else '-'
    print(f"x[{i}] = ({a[i][n]} {sign} {abs(t)})/{a[i][i]} = {x[i]}", end='\n\n')
print('\nThe solution is: ')
for i in range(n):
    print('X%d = %0.5f' %(i,x[i]), end = '\t')

forward elimination

[[144.   12.    1.  279.2]
 [ 64.    8.    1.  177.2]
 [ 25.    5.    1.  106.8]]

[[144.          12.           1.         279.2       ]
 [  0.           2.66666667   0.55555556  53.11111111]
 [  0.           2.91666667   0.82638889  58.32777778]]

[[1.44000000e+02 1.20000000e+01 1.00000000e+00 2.79200000e+02]
 [0.00000000e+00 2.66666667e+00 5.55555556e-01 5.31111111e+01]
 [0.00000000e+00 0.00000000e+00 2.18750000e-01 2.37500000e-01]]

backward substitution

x[2] = 0.23749999999999716/0.2187499999999999 = 1.0857142857142732

x[1] = (53.111111111111114 - 0.6031746031745963)/2.666666666666667 = 19.690476190476193

x[0] = (279.2 - 237.3714285714286)/144.0 = 0.2904761904761901


The solution is: 
X0 = 0.29048	X1 = 19.69048	X2 = 1.08571	

<center>
<hr>
<font size="20" color='Blue' >Gauss Seidel Method</font>
<hr>
</center>

In [140]:
mat = np.array([[25,5,1],[64,8,1],[144,12,1]])
vec_b = np.array([106.8,177.2,279.2])
print(mat)
print(vec_b)

[[ 25   5   1]
 [ 64   8   1]
 [144  12   1]]
[106.8 177.2 279.2]


In [141]:
def seidel(a, x ,b):
    #Finding length of a(3)       
    n = len(a)                   
    # for loop for 3 times as to calculate x, y , z
    for j in range(0, n):        
        # temp variable d to store b[j]
        d = b[j]                  

        # to calculate respective xi, yi, zi
        for i in range(0, n):     
            if(j != i):
                d-=a[j][i] * x[i]
        # updating the value of our solution        
        x[j] = d / a[j][j]
    # returning our updated solution           
    return x    

x=[1,2,5]

for i in range(0, 10):
    x = seidel(a, x, vec_b)
    print(x)



[np.float64(0.5402777777777777), np.float64(65.40833333333332), np.float64(1276.3428571428578)]
[np.float64(-13.572519841269845), np.float64(-199.45476190476202), np.float64(1276.3428571428578)]
[np.float64(8.499404761904769), np.float64(-199.45476190476202), np.float64(1276.3428571428578)]
[np.float64(8.499404761904769), np.float64(-199.45476190476202), np.float64(1276.3428571428578)]
[np.float64(8.499404761904769), np.float64(-199.45476190476202), np.float64(1276.3428571428578)]
[np.float64(8.499404761904769), np.float64(-199.45476190476202), np.float64(1276.3428571428578)]
[np.float64(8.499404761904769), np.float64(-199.45476190476202), np.float64(1276.3428571428578)]
[np.float64(8.499404761904769), np.float64(-199.45476190476202), np.float64(1276.3428571428578)]
[np.float64(8.499404761904769), np.float64(-199.45476190476202), np.float64(1276.3428571428578)]
[np.float64(8.499404761904769), np.float64(-199.45476190476202), np.float64(1276.3428571428578)]


In [142]:
mat = np.array([[144,12,1],[64,8,1],[25,5,1]])
vec_b = np.array([279.2,177.2,106.8])
print(mat)
print(vec_b)

x=[1,2,5]

for i in range(0, 100):
    x = seidel(mat, x, vec_b)
    print(x)


[[144  12   1]
 [ 64   8   1]
 [ 25   5   1]]
[279.2 177.2 106.8]
[np.float64(1.7374999999999998), np.float64(7.625), np.float64(25.237500000000004)]
[np.float64(1.1282118055555554), np.float64(9.969618055555554), np.float64(28.74661458333334)]
[np.float64(0.9084581163194447), np.float64(11.289008246527773), np.float64(27.64350585937502)]
[np.float64(0.8061694109881368), np.float64(12.245206479673026), np.float64(25.419732326931438)]
[np.float64(0.7419290966457796), np.float64(13.037100685967332), np.float64(23.066269154018855)]
[np.float64(0.692281407044258), np.float64(13.728465099393576), np.float64(20.85063932692566)]
[np.float64(0.6500540241691071), np.float64(14.343237890781435), np.float64(18.83245994186514)]
[np.float64(0.6128380928385948), np.float64(14.8932377645581), np.float64(17.01285885624462)]
[np.float64(0.5796408886740152), np.float64(15.3862655335773), np.float64(15.377650115263123)]
[np.float64(0.5499108575125644), np.float64(15.828506875491591), np.float64(13.909694

In [143]:
#x=[0.3,20,1]
x = x_bk

for i in range(0, 10):
    x = seidel(mat, x, vec_b)
    print(x)


[ 0.29047619 19.69047619  1.08571429]
[ 0.29047619 19.69047619  1.08571429]
[ 0.29047619 19.69047619  1.08571429]
[ 0.29047619 19.69047619  1.08571429]
[ 0.29047619 19.69047619  1.08571429]
[ 0.29047619 19.69047619  1.08571429]
[ 0.29047619 19.69047619  1.08571429]
[ 0.29047619 19.69047619  1.08571429]
[ 0.29047619 19.69047619  1.08571429]
[ 0.29047619 19.69047619  1.08571429]


<font size="7" color='Black' >Not converging, however, let's see the results of example 2</font>


In [144]:
x = [1,3,4]
mat = np.array([[12,3,-5],[1,5,3],[3,7,13]])
vec_b = np.dot(mat,x) #np.array([1,28,76])
print(mat)
print(vec_b)

[[12  3 -5]
 [ 1  5  3]
 [ 3  7 13]]
[ 1 28 76]


In [ ]:
x=[1,0,1] # initial guess, true x = [1,2,4]

for i in range(0, 10):
    x = seidel(mat, x, vec_b)
    print(f'{i}-th iteration: {x}')

0-th iteration: [np.float64(0.5), np.float64(4.9), np.float64(3.092307692307692)]
1-th iteration: [np.float64(0.14679487179487158), np.float64(3.7152564102564107), np.float64(3.811755424063116)]
2-th iteration: [np.float64(0.7427506574621955), np.float64(3.164396614069691), np.float64(3.9708439791635053)]
3-th iteration: [np.float64(0.946752504467371), np.float64(3.028143111608423), np.float64(3.997133900410687)]
4-th iteration: [np.float64(0.9917700139356805), np.float64(3.0033656569664515), np.float64(4.0000869507252155)]
5-th iteration: [np.float64(0.9991948152272269), np.float64(3.000108866519425), np.float64(4.0001271914371035)]
6-th iteration: [np.float64(1.00002577980227), np.float64(2.9999185291772834), np.float64(4.0000379197194)]
7-th iteration: [np.float64(1.0000361675887623), np.float64(2.999970014650607), np.float64(4.000007799590728)]
8-th iteration: [np.float64(1.000010746166818), np.float64(2.9999931710121994), np.float64(4.000001197262628)]
9-th iteration: [np.float64(

<font size="7" color='Black' >It is converging...</font>


<center>
<hr>
<font size="20" color='Blue' >LU Decomposition Method </font>
<hr>
</center>

<font size="7" color='Black' >Do little Method </font>


In [146]:
# Python3 Program to decompose
# a matrix into lower and
# upper triangular matrix
MAX = 100

def luDecomposition(mat, n):

	lower = [[0.0 for x in range(n)]
			for y in range(n)]
	upper = [[0.0 for x in range(n)]
			for y in range(n)]

	# Decomposing matrix into Upper
	# and Lower triangular matrix
	for i in range(n):

		# Upper Triangular
		for k in range(i, n):

			# Summation of L(i, j) * U(j, k)
			sum = 0.0
			for j in range(i):
				sum += (lower[i][j] * upper[j][k])

			# Evaluating U(i, k)
			upper[i][k] = mat[i][k] - sum

		for l in range(n):

			# Upper
			for m in range(n):
				print(f'{upper[l][m]:0.3}', end="\t")
			print("")
		print("")

		# Lower Triangular
		for k in range(i, n):
			if (i == k):
				lower[i][i] = 1.0 # Diagonal as 1
			else:

				# Summation of L(k, j) * U(j, i)
				sum = 0.0
				for j in range(i):
					sum += (lower[k][j] * upper[j][i])

				# Evaluating L(k, i)
				# lower[k][i] = int((mat[k][i] - sum) / upper[i][i])
				lower[k][i] = ((mat[k][i] - sum) / upper[i][i])

	R = np.matmul(np.array(lower),np.array(upper))
	
	# setw is for displaying nicely
	print("Lower Triangular\t\tUpper Triangular\t\tLower*Upper")

	# Displaying the result :
	for i in range(n):

		# Lower
		for j in range(n):
			print(f'{lower[i][j]:0.3}', end="\t")
		print("", end="\t")

		# Upper
		for j in range(n):
			print(f'{upper[i][j]:0.3}', end="\t")
		print("", end='\t')

		# R
		for j in range(n):
			print(f'{R[i][j]:0.3}', end="\t")
		print("")
	


# Driver code

mat = np.array([[25.0,5.0,1.0],[64.0,8.0,1.0],[144.0,12.0,1.0]])

luDecomposition(mat, 3)

# This code is contributed by mits


25.0	5.0	1.0	
0.0	0.0	0.0	
0.0	0.0	0.0	

25.0	5.0	1.0	
0.0	-4.8	-1.56	
0.0	0.0	0.0	

25.0	5.0	1.0	
0.0	-4.8	-1.56	
0.0	0.0	0.7	

Lower Triangular		Upper Triangular		Lower*Upper
1.0	0.0	0.0		25.0	5.0	1.0		25.0	5.0	1.0	
2.56	1.0	0.0		0.0	-4.8	-1.56		64.0	8.0	1.0	
5.76	3.5	1.0		0.0	0.0	0.7		1.44e+02	12.0	1.0	


In [147]:
import scipy.linalg
A = np.array([[25.0,5.0,1.0],[64.0,8.0,1.0],[144.0,12.0,1.0]])
P, L, U = scipy.linalg.lu(A)
print(P)
print(L)
print(U)

R = np.matmul(L,U)
print(np.matmul(P,R))

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1.         0.         0.        ]
 [0.17361111 1.         0.        ]
 [0.44444444 0.91428571 1.        ]]
[[144.          12.           1.        ]
 [  0.           2.91666667   0.82638889]
 [  0.           0.          -0.2       ]]
[[ 25.   5.   1.]
 [ 64.   8.   1.]
 [144.  12.   1.]]


<center>
<hr>
<font size="20" color='Blue' >That's the end... </font>
<hr>
</center>